### ISSUE TITLE
Cannot import from io-ts-types

### ISSUE THREAD

**Issue by joefiorini** [gcanti/io-ts-types#104]
I'm trying to import from `io-ts-types` and I get an error that `node_modules/io-ts-types/lib/index.d.ts` is not a module. I've tried reinstalling it a few times, to no avail. It appears the `index.d.ts` is empty, which may be the cause of the issue? I forked a [sample repo in which](https://github.com/joefiorini/i-am-going-crazy) I was immediately able to reproduce the issue. Just clone it, run `yarn install` and run `yarn tsc`. You should see the error quoted above.

All libraries should be latest as of filing this issue.
TypeScript version: 3.6.2
io-ts: 2.0.1
io-ts-types: 0.5.0

**Comment by giogonzo** [comment]
Currently `index.ts` is just an empty file 😕 I'm not sure wether this was intentional or not

In any case I'd always prefer specific imports (e.g. `import { IntFromString } from "io-ts-types/lib/IntFromString";`) so as to be able to build without installing undesired dependencies (i.e. `monocle-ts` is only needed for a subset of the combinators)

**Comment by sgronblo** [comment]
I also ran into this immediately. I think it would help if the README.md included some concrete examples of how to use the library.
